"""initial_schema

Revision ID: 33854f306c67
Revises: 
Create Date: 2026-03-04 20:01:49.956879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33854f306c67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subject_type', sa.String(length=20), nullable=False),
        sa.Column('correct_numeric_answer', sa.Float(), nullable=True),
        sa.Column('numeric_tolerance', sa.Float(), nullable=True),
        sa.Column('expected_unit', sa.String(length=50), nullable=True),
        sa.Column('hybrid_numerical_weight', sa.Float(), nullable=True),
        sa.Column('hybrid_descriptive_weight', sa.Float(), nullable=True),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('answer_key', sa.Text(), nullable=False),
        sa.Column('max_marks', sa.Integer(), nullable=False),
        sa.Column('evaluation_level', sa.String(length=16), nullable=False),
        sa.Column('concepts', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('question_id', sa.UUID(), nullable=False),
        sa.Column('student_image_path', sa.String(length=512), nullable=False),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('evaluation_details', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('per_question_scores', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('total_score', sa.Float(), nullable=True),
        sa.Column('percentage', sa.Float(), nullable=True),
        sa.Column('manual_override', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('final_score', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('submission_id', sa.UUID(), nullable=False),
        sa.Column('evaluation_snapshot', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_logs')
    op.drop_table('submissions')
    op.drop_table('questions')
    # ### end Alembic commands ###
